# Tarea: CASO PRÁCTICO 1: ANÁLISIS DE DATOS CON PANDAS

En este caso práctico usted es el Data Scientist de la empresa Mobpatec, dedicada a la fabricación de mobiliario de oficina y dispositivos tecnológicos. Dispone de una serie de fuentes de datos y le piden dar respuesta a varias preguntas en base al análisis de datos descrito en las instrucciones.

In [34]:
# Importar librerias desde la carpeta "./Datasets/CASO PRÁCTICO 1/"
import pandas as pd
df_clientes = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Clientes.xlsx", sheet_name= "Sheet1")
df_ventas = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Ventas.xlsx", sheet_name= "Sheet1")
df_productos = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Productos.xlsx", sheet_name= "Sheet1")
#df_poblacion = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Reporte Beneficios.xlsx", sheet_name= "Beneficios_cat_pais")
df_rpc = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Exportado_RPC.xlsx", sheet_name= "Sheet2")
df_PIB = pd.read_excel(r"./Datasets/CASO PRÁCTICO 1/Exportado_Población_PIB.xlsx", sheet_name= "Sheet1")
df_poblacion = df_PIB[["Country", "Population -2017"]]
df_clientes

,ID Cliente,Nombre cliente,Segmento,País,Ciudad,Estado,Código Postal,Región
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South
...,...,...,...,...,...,...,...,...
788,CJ-11875,Carl Jackson,Corporate,Romania,NaN,NaN,NaN,NaN
789,RS-19870,Roy Skaria,Home Office,Romania,NaN,NaN,NaN,NaN
790,SC-20845,Sung Chung,Consumer,Romania,NaN,NaN,NaN,NaN
791,RE-19405,Ricardo Emerson,Consumer,Romania,NaN,NaN,NaN,NaN
792,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN

In [30]:
# PREGUNTA 1: ¿Cuáles son las dimensiones (registros x columnas) de cada dataframe?
print("Las dimenciones del dataframe clientes son", df_clientes.shape)
print("Las dimenciones del dataframe ventas son", df_ventas.shape)
print("Las dimenciones del dataframe productos son", df_productos.shape)
print("Las dimenciones del dataframe poblacion son", df_poblacion.shape)
print("Las dimenciones del dataframe rpc son", df_rpc.shape)
print("Las dimenciones del dataframe PIB son", df_PIB.shape)

Las dimenciones del dataframe clientes son (793, 8)
Las dimenciones del dataframe ventas son (9994, 8)
Las dimenciones del dataframe productos son (1864, 5)
Las dimenciones del dataframe poblacion son (189, 2)
Las dimenciones del dataframe rpc son (36, 2)
Las dimenciones del dataframe PIB son (189, 8)

In [33]:
# ¿Existen valores NaN en nuestras fuentes?
df_clientes.isnull().sum()

ID Cliente          0
Nombre cliente      0
Segmento            0
País                0
Ciudad            455
Estado            455
Código Postal     455
Región            455
dtype: int64